sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
script:
- "./gradlew build"
- docker build --no-cache --pull -t wisvch/choice:$TRAVIS_BUILD_NUMBER .
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push wisvch/choice:$TRAVIS_BUILD_NUMBER;
  fi
notifications:
  slack:
    rooms:
      secure: mFXgwiGV/mYigbO1GrdKesAOtIilaf2Yb++zJgyBFMqWgMYWe5UqSfOl7vmWgvsu8bx1mBWAQA70L2lo/0fn5Bf29FluhJREW05QsUJfUN6+Y3/WFUpbpn/sf3ao802Grnc8cO/7/jYRr4FszlZZ1gK5ZtfBbvq18qyKs504rmuHNWMVhnFGxk/KszkdFBdHn9Q1BqhjWn1OvE8gJiWWVhJLjBjlsOYTmXKiM2g0G/MuveDEnO4l2jUngI9m7U+nrvrjZrRJrAV2VO8iw3kl6jJXuNUEDx3tuTJ1JYYyLBB/yp/9Ak6pxyVo7eyc8WfBfQl2mqWlD60wfh8y96ZNZLAR7jOJKYbahLe5C+ZWGM5gse6lPhPn2MCvy6dv1T3rcODEYJcetikXAP8ZQrF4s6xd6zol3yamKwAOtanfUleSd3Rcwc8yoDmzGP3ZPtT2tlA+QGNhZdUzRfzu8UBeebu1oB+TGNTQh9EnTnXFNVuxZI0GLmyH5rRe9+QlVOypAKxDq5xCkZSkahUzBzgJ83WrsE15ZpadgbfC6vhzQhIjaSj4pV0CfsGw7AmCXetDPo4MxuatewjydtuhEX+D3HfcqgI7Sg6Sgs2mJkLPPWzYvCv0lAWLJcBYW9cbfDU6gopj0QO9BiLxaChXpuefXyS9jxLlkq5Bq4jKiba8OJg=
