## DATABASE PROPERTIES
spring:
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:choice
    username: sa
    password:
  jpa:
    database: HSQL
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties.hibernate.default_schema: PUBLIC
  security:
    oauth2:
      client:
        provider:
          wisvchconnect:
            issuer-uri: https://connect.ch.tudelft.nl
        registration:
          wisvchconnect:
            client-id: localhost-spring-dev
            client-secret: Hvw51WUpYdSRhJ6hrxNSNQyXK0jv3M6-dRxVhfUhEuVz9PvH8hVMz51SeGajsIVT_C5l0KyzjrnfvNyGzbiW3A
            scope:
              - openid
              - profile
              - email
              - ldap

server:
  port: 8080
  servlet.contextPath: /choice2