## DATABASE PROPERTIES
spring:
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:choice
    username: sa
    password:
  jpa:
    database: HSQL
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties.hibernate.default_schema: PUBLIC

server:
  port: 8080
