## DATABASE PROPERTIES
spring:
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/<database>
    username: <username>
    password: <password>
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate.default_schema: PUBLIC

  thymeleaf:
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html

  http:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB

  security:
    oauth2:
      client:
        provider:
          wisvchconnect:
            issuer-uri: https://connect.ch.tudelft.nl
        registration:
          wisvchconnect:
            scope:
              - openid
              - profile
              - email
              - ldap

server:
  port: 8080
  servlet.contextPath: /choice2

security.basic.enabled: false

wisvch:
  connect:
    admin-groups:
      - <ldap-group>