## DATABASE PROPERTIES
spring:
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/<database>
    username: <username>
    password: <password>
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties.hibernate.default_schema: PUBLIC

  thymeleaf:
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html

  http:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB

server:
  port: 8080
  context-path: /choice2

security.basic.enabled: false

wisvch:
  connect:
    issuerUri: https://connect.ch.tudelft.nl/
    clientUri: http://localhost:8080/choice2
    admin-groups: <ldap-group>